name: binav_avts
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  
  # Plugin Router 
  go_router: ^12.0.1

  # Plugin State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Plugin menyimpan data Cookies
  shared_preferences: ^2.2.2
  dio: ^5.3.3

  # Plugin Socket Channel
  web_socket_channel: ^2.4.0

  # Loader UI
  flutter_easyloading: ^3.0.5
  loader_overlay: ^2.3.2

  # Alert UI 
  flutter_styled_toast: ^2.2.1
  lottie: ^2.7.0

  # Assets Manager
  flutter_svg: ^2.0.9

  # Fonts
  google_fonts: ^6.1.0

  # Carousel UI
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0

  # Pagination Button UI
  pagination_flutter: ^0.0.8
  dropdown_textfield: ^1.0.8
  responsive_ui: ^3.0.1
  dropdown_search: ^5.0.6
  flutter_map: ^6.0.1
  xml: ^6.3.0
  flutter_map_cancellable_tile_provider: ^1.0.0
  snapping_sheet: ^3.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/kapal.png
    - assets/model_kapal.jpg
    - assets/kml/cta.kml
    - assets/lottie/
    - assets/kml/format_pipa.kml
    - assets/kml/
    - assets/xml/kapal.xml
    - assets/xml/
    - assets/
    - assets/background-login.jpg
    - assets/maps-icon.png
    - assets/xml_icon.png
    - assets/add_file_icon.png
    - assets/xml_icon2.png
    - assets/lottie/mail.json
    - assets/lottie/animation_delete.json
    - assets/logo.png
    - assets/intro1.jpg
    - assets/intro2.jpg
    - assets/intro3.jpg
    - assets/intro4.jpg
    - assets/vector1.jpg
    - assets/vector2.svg

